// DO NOT EDIT THIS FILE
// IT IS AUTO GENERATED BY ANGULAR-CLI
import {ProductRoot} from './product/product-root.component';

export const CliRouteConfig = [
  {path: '/product/...', name: 'ProductRoot', component: ProductRoot},
];